//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamOverlay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StreamOverlayEntities : DbContext
    {
        public StreamOverlayEntities()
            : base("name=StreamOverlayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OveralyData> OveralyDatas { get; set; }
    
        public virtual ObjectResult<string> GetFirstEntry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFirstEntry");
        }
    }
}
